services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    networks:
      - app-decide_default
    expose:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: unless-stopped
    volumes:
      - ./nominatim-data:/var/lib/postgresql/16/main

  geocoding-service:
    container_name: geocoding-service
    build:
      context: .
    ports:
      - "8082:80"
      - "8888:8888"  # eTranslation callback port
    networks:
      - app-decide_default
    environment:
      MU_SPARQL_ENDPOINT: http://app-decide-virtuoso-1:8890/sparql
      ETRANSLATION_USERNAME: ''
      ETRANSLATION_PASSWORD: ''
      ETRANSLATION_BASE_URL: 'https://language-tools.ec.europa.eu/etranslation/api'
      ETRANSLATION_DOMAIN: 'GEN'
      ETRANSLATION_TIMEOUT: '60'
      ETRANSLATION_CALLBACK_TIMEOUT: '180'
      ETRANSLATION_CALLBACK_HOST: '0.0.0.0'
      ETRANSLATION_CALLBACK_PORT: '8888'
      NGROK_AUTHTOKEN: ''
      ETRANSLATION_CALLBACK_URL: ''
      EXPECTED_TASK_PREDICATE: 'http://www.w3.org/ns/adms#status'
      EXPECTED_TASK_OBJECT: 'http://redpencil.data.gift/id/concept/JobStatus/scheduled'
    volumes:
      - ./:/app
      - ./config.json:/app/config.json:ro  # Mount config as read-only

networks:
  app-decide_default:
    external: true
